version: "3"
services:
    main-db:
        image: postgres:15.3-bullseye
        container_name: main-db
        environment:
            - POSTGRES_USER=sumit
            - POSTGRES_PASSWORD=main123
        ports:
            - 5432:5432
        restart: unless-stopped
        # Uncomment the line below if you want to persist data
        # volumes:
        #   - ./data:/var/lib/postgresql/data
